<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Curso', 'doctrine');

/**
 * BaseCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Tema
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getTema()   Returns the current record's "Tema" collection
 * @method Curso               setId()     Sets the current record's "id" value
 * @method Curso               setNombre() Sets the current record's "nombre" value
 * @method Curso               setTema()   Sets the current record's "Tema" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tema', array(
             'local' => 'id',
             'foreign' => 'tema_id'));
    }
}