<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contenido', 'doctrine');

/**
 * BaseContenido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $titulo
 * @property integer $tema_id
 * @property integer $orden
 * @property Tema $Tema
 * @property Doctrine_Collection $Cuestionario
 * @property Doctrine_Collection $Texto
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getTitulo()       Returns the current record's "titulo" value
 * @method integer             getTemaId()       Returns the current record's "tema_id" value
 * @method integer             getOrden()        Returns the current record's "orden" value
 * @method Tema                getTema()         Returns the current record's "Tema" value
 * @method Doctrine_Collection getCuestionario() Returns the current record's "Cuestionario" collection
 * @method Doctrine_Collection getTexto()        Returns the current record's "Texto" collection
 * @method Contenido           setId()           Sets the current record's "id" value
 * @method Contenido           setTitulo()       Sets the current record's "titulo" value
 * @method Contenido           setTemaId()       Sets the current record's "tema_id" value
 * @method Contenido           setOrden()        Sets the current record's "orden" value
 * @method Contenido           setTema()         Sets the current record's "Tema" value
 * @method Contenido           setCuestionario() Sets the current record's "Cuestionario" collection
 * @method Contenido           setTexto()        Sets the current record's "Texto" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Alejandro Lorente. eidansoft ARROBA gmail PUNTO com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContenido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contenido');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('tema_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tema', array(
             'local' => 'tema_id',
             'foreign' => 'id'));

        $this->hasMany('Cuestionario', array(
             'local' => 'id',
             'foreign' => 'contenido_id'));

        $this->hasMany('Texto', array(
             'local' => 'id',
             'foreign' => 'contenido_id'));
    }
}