<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoRespuestaAlternativa', 'doctrine');

/**
 * BaseTipoRespuestaAlternativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $respuesta_id
 * @property Respuesta $Respuesta
 * @property Doctrine_Collection $RespuestaAlternativa
 * 
 * @method integer                  getId()                   Returns the current record's "id" value
 * @method integer                  getRespuestaId()          Returns the current record's "respuesta_id" value
 * @method Respuesta                getRespuesta()            Returns the current record's "Respuesta" value
 * @method Doctrine_Collection      getRespuestaAlternativa() Returns the current record's "RespuestaAlternativa" collection
 * @method TipoRespuestaAlternativa setId()                   Sets the current record's "id" value
 * @method TipoRespuestaAlternativa setRespuestaId()          Sets the current record's "respuesta_id" value
 * @method TipoRespuestaAlternativa setRespuesta()            Sets the current record's "Respuesta" value
 * @method TipoRespuestaAlternativa setRespuestaAlternativa() Sets the current record's "RespuestaAlternativa" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Alejandro Lorente. eidansoft ARROBA gmail PUNTO com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoRespuestaAlternativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipoRespuestaAlternativa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('respuesta_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Respuesta', array(
             'local' => 'respuesta_id',
             'foreign' => 'id'));

        $this->hasMany('RespuestaAlternativa', array(
             'local' => 'id',
             'foreign' => 'tipoRespuestaAlternativa_id'));
    }
}