<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RespuestasTipoPreguntaAlternativa', 'doctrine');

/**
 * BaseRespuestasTipoPreguntaAlternativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipoPreguntaAlternativa_id
 * @property string $texto
 * @property TipoPreguntaAlternativa $TipoPreguntaAlternativa
 * 
 * @method integer                           getId()                         Returns the current record's "id" value
 * @method integer                           getTipoPreguntaAlternativaId()  Returns the current record's "tipoPreguntaAlternativa_id" value
 * @method string                            getTexto()                      Returns the current record's "texto" value
 * @method TipoPreguntaAlternativa           getTipoPreguntaAlternativa()    Returns the current record's "TipoPreguntaAlternativa" value
 * @method RespuestasTipoPreguntaAlternativa setId()                         Sets the current record's "id" value
 * @method RespuestasTipoPreguntaAlternativa setTipoPreguntaAlternativaId()  Sets the current record's "tipoPreguntaAlternativa_id" value
 * @method RespuestasTipoPreguntaAlternativa setTexto()                      Sets the current record's "texto" value
 * @method RespuestasTipoPreguntaAlternativa setTipoPreguntaAlternativa()    Sets the current record's "TipoPreguntaAlternativa" value
 * 
 * @package    themario
 * @subpackage model
 * @author     Alejandro Lorente. eidansoft ARROBA gmail PUNTO com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRespuestasTipoPreguntaAlternativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('respuestasTipoPreguntaAlternativa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipoPreguntaAlternativa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoPreguntaAlternativa', array(
             'local' => 'tipoPreguntaAlternativa_id',
             'foreign' => 'id'));
    }
}