<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tema', 'doctrine');

/**
 * BaseTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $curso_id
 * @property Curso $Curso
 * @property Doctrine_Collection $Contenido
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method integer             getCursoId()   Returns the current record's "curso_id" value
 * @method Curso               getCurso()     Returns the current record's "Curso" value
 * @method Doctrine_Collection getContenido() Returns the current record's "Contenido" collection
 * @method Tema                setId()        Sets the current record's "id" value
 * @method Tema                setNombre()    Sets the current record's "nombre" value
 * @method Tema                setCursoId()   Sets the current record's "curso_id" value
 * @method Tema                setCurso()     Sets the current record's "Curso" value
 * @method Tema                setContenido() Sets the current record's "Contenido" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tema');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('curso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Curso', array(
             'local' => 'curso_id',
             'foreign' => 'id'));

        $this->hasMany('Contenido', array(
             'local' => 'id',
             'foreign' => 'tema_id'));
    }
}