<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Alumno', 'doctrine');

/**
 * BaseAlumno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $CuestionAlumnoRespuesta
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getNombre()                  Returns the current record's "nombre" value
 * @method Doctrine_Collection getCuestionAlumnoRespuesta() Returns the current record's "CuestionAlumnoRespuesta" collection
 * @method Alumno              setId()                      Sets the current record's "id" value
 * @method Alumno              setNombre()                  Sets the current record's "nombre" value
 * @method Alumno              setCuestionAlumnoRespuesta() Sets the current record's "CuestionAlumnoRespuesta" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Alejandro Lorente. eidansoft ARROBA gmail PUNTO com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CuestionAlumnoRespuesta', array(
             'local' => 'id',
             'foreign' => 'alumno_id'));
    }
}