<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cuestion', 'doctrine');

/**
 * BaseCuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pregunta
 * @property integer $cuestionario_id
 * @property ContenidoTipoCuestionario $ContenidoTipoCuestionario
 * @property Doctrine_Collection $TipoPreguntaAlternativa
 * @property Doctrine_Collection $TipoPreguntaCorta
 * 
 * @method integer                   getId()                        Returns the current record's "id" value
 * @method string                    getPregunta()                  Returns the current record's "pregunta" value
 * @method integer                   getCuestionarioId()            Returns the current record's "cuestionario_id" value
 * @method ContenidoTipoCuestionario getContenidoTipoCuestionario() Returns the current record's "ContenidoTipoCuestionario" value
 * @method Doctrine_Collection       getTipoPreguntaAlternativa()   Returns the current record's "TipoPreguntaAlternativa" collection
 * @method Doctrine_Collection       getTipoPreguntaCorta()         Returns the current record's "TipoPreguntaCorta" collection
 * @method Cuestion                  setId()                        Sets the current record's "id" value
 * @method Cuestion                  setPregunta()                  Sets the current record's "pregunta" value
 * @method Cuestion                  setCuestionarioId()            Sets the current record's "cuestionario_id" value
 * @method Cuestion                  setContenidoTipoCuestionario() Sets the current record's "ContenidoTipoCuestionario" value
 * @method Cuestion                  setTipoPreguntaAlternativa()   Sets the current record's "TipoPreguntaAlternativa" collection
 * @method Cuestion                  setTipoPreguntaCorta()         Sets the current record's "TipoPreguntaCorta" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Alejandro Lorente. eidansoft ARROBA gmail PUNTO com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuestion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pregunta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cuestionario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContenidoTipoCuestionario', array(
             'local' => 'cuestionario_id',
             'foreign' => 'id'));

        $this->hasMany('TipoPreguntaAlternativa', array(
             'local' => 'id',
             'foreign' => 'cuestion_id'));

        $this->hasMany('TipoPreguntaCorta', array(
             'local' => 'id',
             'foreign' => 'cuestion_id'));
    }
}