<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Respuesta', 'doctrine');

/**
 * BaseRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Doctrine_Collection $TipoRespuestaCorta
 * @property Doctrine_Collection $TipoRespuestaAlternativa
 * @property Doctrine_Collection $CuestionAlumnoRespuesta
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method Doctrine_Collection getTipoRespuestaCorta()       Returns the current record's "TipoRespuestaCorta" collection
 * @method Doctrine_Collection getTipoRespuestaAlternativa() Returns the current record's "TipoRespuestaAlternativa" collection
 * @method Doctrine_Collection getCuestionAlumnoRespuesta()  Returns the current record's "CuestionAlumnoRespuesta" collection
 * @method Respuesta           setId()                       Sets the current record's "id" value
 * @method Respuesta           setTipoRespuestaCorta()       Sets the current record's "TipoRespuestaCorta" collection
 * @method Respuesta           setTipoRespuestaAlternativa() Sets the current record's "TipoRespuestaAlternativa" collection
 * @method Respuesta           setCuestionAlumnoRespuesta()  Sets the current record's "CuestionAlumnoRespuesta" collection
 * 
 * @package    themario
 * @subpackage model
 * @author     Alejandro Lorente. eidansoft ARROBA gmail PUNTO com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRespuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('respuesta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TipoRespuestaCorta', array(
             'local' => 'id',
             'foreign' => 'respuesta_id'));

        $this->hasMany('TipoRespuestaAlternativa', array(
             'local' => 'id',
             'foreign' => 'respuesta_id'));

        $this->hasMany('CuestionAlumnoRespuesta', array(
             'local' => 'id',
             'foreign' => 'respuesta_id'));
    }
}