<?php

/**
 * ContenidoTipoCuestionarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenidoTipoCuestionarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContenidoTipoCuestionarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContenidoTipoCuestionario');
    }
}