<?php

/**
 * CuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cuestion');
    }
}