<?php

/**
 * RespuestaCortaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RespuestaCortaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RespuestaCortaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RespuestaCorta');
    }
}