<?php

/**
 * TextoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TextoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TextoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Texto');
    }
}