<?php

/**
 * TipoRespuestaAlternativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoRespuestaAlternativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoRespuestaAlternativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoRespuestaAlternativa');
    }
}