<?php

/**
 * TipoPreguntaCortaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoPreguntaCortaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoPreguntaCortaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoPreguntaCorta');
    }
}