# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
    frontend:
        tituloApp:                      'TheMario'
        
        msgSeleccionaCurso:             'Selecciona el curso que quieres trabajar...'
        
        msgSelecionaTema:               'Selecciona el tema del curso que quieres trabajar...'
        
        msgSelecionaContenido:          'Selecciona el contenido del tema que quieres trabajar...'
        
        msgContenidoNoDefinido:         'Este contenido a&uacute;n no est&aacute; definido. Disculpa las molestias.'
        
        tituloErrorGuardaCuestionario:  'Error'
        
        msgErrorGuardaCuestionario:     'Ha ocurrido un error al salvar la informaci&oacute;n'

        tituloExitoGuardaCuestionario:  'Datos guardados'
        
        msgExitoGuardaCuestionario:     'Las respuestas se han guardado correctamente. ¡Gracias!'
