<?php

/**
 * ContenidoTipoTextoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenidoTipoTextoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContenidoTipoTextoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContenidoTipoTexto');
    }

    
    public function getTextoDeContenido($contenido_id)
    {
        return Doctrine_Core::getTable('ContenidoTipoTexto')->createQuery('a')->where('contenido_id = ?', $contenido_id)->execute();
    }
}
