<?php

/**
 * CuestionarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuestionarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuestionarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cuestionario');
    }
}