<?php

/**
 * RespuestaTipoPreguntaAlternativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RespuestaTipoPreguntaAlternativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RespuestaTipoPreguntaAlternativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RespuestaTipoPreguntaAlternativa');
    }
        
    public function getRespuestaDeTipoPreguntaId($tipoPregunta_id)
    {
        return Doctrine_Core::getTable('RespuestaTipoPreguntaAlternativa')->createQuery('j')->where('tipoPreguntaAlternativa_id = ?', $tipoPregunta_id)->execute();
    }
}
