<?php

/**
 * RespuestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RespuestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RespuestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Respuesta');
    }
    
    public function getTipoRespuesta($respuesta_id)
    {
        //consulto todas las tablas de mi esquema denominadas "TipoRespuesta....."
        $pdo = Doctrine_Manager::connection()->getDbh();
        // disable constraint checking for mysql when innodb tables are used
        $pdo->exec('SET foreign_key_checks = 0');
        // get all tables
        $sql = "SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = (SELECT schema() FROM DUAL) and
                      UPPER(table_name) LIKE UPPER('tipoRespuesta%')";
        $tablasRespuesta = $pdo->query($sql);
     
        foreach ($tablasRespuesta as $tabla){
            $encontrado = Doctrine_Core::getTable($tabla['table_name'])->createQuery('j')->where('respuesta_id = ?', $respuesta_id)->count();
            if ($encontrado > 0){
                return $tabla['table_name'];
            }
        }
        //si llego a este punto, significa que no se ha encontrado ningun tipo respuesta a la cuestion, asi que lanzo excepcion
        throw new sfException('Response-type with id('.$respuesta_id.') not found. May be need create.');
    }
}
