<?php

/**
 * TipoRespuestaCortaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoRespuestaCortaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoRespuestaCortaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoRespuestaCorta');
    }
}